#spring:
#  application:
#    name: gateway-service
#  profiles:
#    active: dev
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yaml
#    gateway:
#      # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true # 服务名称转成小写
#
#      routes:
#        - id: market-service
#          uri: lb://market-service
#          predicates:
#            - Path=/market/**
#            - After=2022-01-20T17:42:47.789-07:00[America/Denver]
#            - Method=GET
#
#      globalcors: # 全局的跨域处理
#        add-to-simple-url-handler-mapping: true # 解决options请求被拦截问题
#        corsConfigurations:
#          '[/**]':  # 对所有路径生效的跨域配置
#            allowedOriginPatterns: # 允许的源（注意：生产环境不建议用"*"，需指定具体域名）
#              - "*"
#            allowedMethods: # 允许的HTTP方法
#              - "GET"
#              - "POST"
#              - "DELETE"
#              - "PUT"
#              - "OPTIONS"
#            allowedHeaders: "*" # 允许的请求头
#            allowCredentials: true # 是否允许携带Cookie
#            maxAge: 360000 # 预检请求有效期（毫秒）